<a href="https://colab.research.google.com/github/sairas2124/Gradient_descent-/blob/main/NLP_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests

url = "https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1"

response = requests.get(url)
data = response.json()

# Extract movie overviews (text data)
texts = [movie['overview'] for movie in data['results']]

# Take one sample
text = texts[0]
print(text)

Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.


In [2]:
import re
import nltk

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Chat word dictionary
chat_words = {
    "u": "you",
    "r": "are",
    "lol": "laughing",
    "omg": "oh my god"
}

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):

    # 1. Lowercase
    text = text.lower()

    # 2. Remove HTML tags
    text = re.sub(r'<.*?>', '', text)

    # 3. Remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)

    # 4. Remove punctuation and special characters
    text = re.sub(r'[^a-z\s]', '', text)

    # 5. Chat word treatment
    words = text.split()
    words = [chat_words.get(word, word) for word in words]

    # 6. Tokenization
    tokens = word_tokenize(" ".join(words))

    # 7. Remove stopwords
    tokens = [word for word in tokens if word not in stop_words]

    # 8. Lemmatization
    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    return " ".join(tokens)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [3]:
cleaned_texts = [clean_text(t) for t in texts]

# Show result
print("Original:\n", texts[0])
print("\nCleaned:\n", cleaned_texts[0])

Original:
 Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.

Cleaned:
 imprisoned double murder wife lover upstanding banker andy dufresne begin new life shawshank prison put accounting skill work amoral warden long stretch prison dufresne come admired inmate including older prisoner named red integrity unquenchable sense hope


METHODS OF CONVETRING TEXT INTO NUMBER

In [1]:
#BoW(bag your words)
from sklearn.feature_extraction.text import CountVectorizer

texts = ["I love NLP", "I love AI"]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)

print(X.toarray())

[[0 1 1]
 [1 1 0]]


In [2]:
#Bigram
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(ngram_range=(2,2))  # only bigrams
X = vectorizer.fit_transform(texts)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['love ai' 'love nlp']
[[0 1]
 [1 0]]


In [5]:
#TD-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

texts = ["I love NLP", "I love AI"]

vectorizer = TfidfVectorizer()
#vectorizer = TfidfVectorizer(ngram_range=(1,2))
X = vectorizer.fit_transform(texts)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['ai' 'love' 'nlp']
[[0.         0.57973867 0.81480247]
 [0.81480247 0.57973867 0.        ]]


WORD EMBEDDING

In [2]:
!pip install gensim


In [4]:
#Word2Vec
import numpy as np
import pandas as pd
import gensim
from gensim.models import Word2Vec,KeyedVectors


In [5]:
!pip install wget

  Preparing metadata (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9655 sha256=a85e92eeb6f50198ac337028ba48a552b1cb06f207babcd4503282afe62d031a
  Stored in directory: /root/.cache/pip/wheels/01/46/3b/e29ffbe4ebe614ff224bad40fc6a5773a67a163251585a13a9
Successfully built wget


In [15]:
from nltk.tokenize import word_tokenize
import nltk
from gensim.models import Word2Vec

# Ensure punkt_tab is downloaded (redundant but can fix transient issues)
nltk.download('punkt_tab')

# Sample sentences
sentences = [
    "I love NLP",
    "I love machine learning",
    "NLP is fun",
    "machine learning is powerful"
]

# Tokenize sentences
tokenized = [word_tokenize(sentence.lower()) for sentence in sentences]

# Train Word2Vec model
model = Word2Vec(sentences=tokenized, vector_size=50, window=3, min_count=1)

# Get vector for a word
print(model.wv['nlp'])

# Find similar words
print(model.wv.most_similar('nlp'))

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


[ 1.56351421e-02 -1.90203730e-02 -4.11062239e-04  6.93839323e-03
 -1.87794445e-03  1.67635437e-02  1.80215668e-02  1.30730132e-02
 -1.42324204e-03  1.54208085e-02 -1.70686692e-02  6.41421322e-03
 -9.27599426e-03 -1.01779103e-02  7.17923651e-03  1.07406788e-02
  1.55390287e-02 -1.15330126e-02  1.48667218e-02  1.32509926e-02
 -7.41960062e-03 -1.74912829e-02  1.08749345e-02  1.30195115e-02
 -1.57510047e-03 -1.34197120e-02 -1.41718509e-02 -4.99412045e-03
  1.02865072e-02 -7.33047491e-03 -1.87401194e-02  7.65347946e-03
  9.76895820e-03 -1.28571270e-02  2.41711619e-03 -4.14975407e-03
  4.88066689e-05 -1.97670180e-02  5.38400887e-03 -9.50021297e-03
  2.17529293e-03 -3.15244915e-03  4.39334614e-03 -1.57631524e-02
 -5.43436781e-03  5.32639725e-03  1.06933638e-02 -4.78302967e-03
 -1.90201886e-02  9.01175756e-03]
[('fun', 0.0449172779917717), ('is', -0.014475265517830849), ('powerful', -0.04407211393117905), ('machine', -0.15515565872192383), ('learning', -0.17424817383289337), ('love', -0.206005